
stages:
  - docsearch

docsearch:
  stage: docsearch
  image: docker:latest
  services:
    - docker:dind
  variables:
    ALGOLIA_APP_ID: $ALGOLIA_APP_ID
    ALGOLIA_API_KEY: $ALGOLIA_API_KEY
  script:
    - apk add --no-cache git jq
    - CONFIG=$(cat docsearch.json | jq -r tostring)
    - echo "Running Algolia DocSearch scraper with config: $CONFIG"
    - docker run --env APPLICATION_ID=${ALGOLIA_APP_ID} --env API_KEY=${ALGOLIA_API_KEY} --env "CONFIG=${CONFIG}" algolia/docsearch-scraper
  rules:
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master"'
